language: python

python:
- 3.6

services:
- mysql

branches:
  only:
  - develop

env:
  - DJANGO_VERSION=1.11.2

services:
  - mysql

install:
  - pip install --upgrade pip setuptools
  - pip install -q Django==$DJANGO_VERSION
  - pip install flake8
  - pip install pycups
  - pip install coveralls
  - pip install mysqlclient
  - pip install -q -r requirements.txt

before_script:
  - flake8 bcpp_clinic_subject
  - mysql -e 'create database edc character set utf8;'

script: 
  - coverage run --source=bcpp_clinic_subject manage.py test

after_success:
  - coveralls
