ABLE_TO_PARTICIPATE = 'able'
INITIATION = 'initiation'
MASA_VL_SCHEDULED = 'masa_vl_scheduled'
MENTAL_INCAPACITY = 'Mental Incapacity'
RESEARCH_BLOOD_DRAW = 'Research Blood Draw'
VIRAL_LOAD = 'Viral Load'
